### ISSUE TITLE
Getting the currently playing track on Counterstream

### ISSUE THREAD

**Issue by eficklin** [bhoggard/nowplaying-rb#1]
I hear tell you're having trouble with the Counterstream feed. Unfortunately, Live365 went out of business in January so we're no longer broadcasting through them. There is an API call your app can make to our broadcast server to get the current track.  Just issue an HTTP GET request to this url:

`http://counterstreamradio.net/admin/services.php?q=current_track`

You'll get back a JSON object looking something like this:

```
{
  "Live365":"http://www.live365.com/stations/amcenter",
  "Popup":"http://23.21.68.2/popup.php",
  "TrackInfo": {
    "Composer": "Augusta Read Thomas",
    "Track": "Traces",
    "Album": "traces + magneticfireflies",
    "Year": null,
    "Duration": "14:44"}
}
```

We're currently reworking our broadcast setup, but will continue to support this API call.

**Comment by bhoggard** [comment]
Cool, thanks @eficklin! I will update the code.
